/*
Political Intelligence Platform
- consuma /api/intelligence;
- visualizza heatmap, reti/body politico, predizione AI-like e peso politico reale;
- per modelli AI reali sostituire le euristiche backend con pipeline ML addestrate su storico elettorale.
*/
let INTEL=null, predMayorChart=null, predListChart=null;
async function api(url){const r=await fetch(url,{credentials:'include'});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Errore server');return d}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function kpi(label,value,sub=''){return `<div class="card kpi"><b>${esc(value)}</b><span>${esc(label)}</span><small>${esc(sub)}</small></div>`}
async function loadIntelligence(){try{INTEL=await api('/api/intelligence'); renderSummary(); renderHeatmap(); renderBodyGraph(); renderPrediction(); renderWeight();}catch(e){alert(e.message); location.href='/'}}
function renderSummary(){const s=INTEL.summary; summaryCards.innerHTML=[kpi('Elettori',s.total_electors),kpi('Votanti target/rilevati',`${s.total_voters} / ${s.observed_voters}`),kpi('Sezioni caricate/chiuse',`${s.sections_loaded} / ${s.sections_closed}`),kpi('Voti lista',s.total_list_votes),kpi('Voti sindaco',s.total_mayor_votes),kpi('Voti disgiunti',s.split_vote_count)].join('')}
function heatClass(x,mode){let v=mode==='split'?x.split_rate_pct:mode==='turnout'?x.turnout_pct:mode==='list'?x.top_list_pct:x.top_coalition_pct; if(v>=60)return 'heat5'; if(v>=45)return 'heat4'; if(v>=30)return 'heat3'; if(v>=15)return 'heat2'; return 'heat1'}
function renderHeatmap(){const mode=heatFilter.value, q=(heatSearch.value||'').toLowerCase(); let rows=INTEL.heatmap.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)); heatmapBox.innerHTML=rows.map(x=>`<div class="heatCell ${heatClass(x,mode)}" title="Sezione ${esc(x.section)}"><b>Sez. ${esc(x.section)}</b><span>${mode==='list'?esc(x.top_list||'—'):mode==='split'?'Disgiunti '+x.split_rate_pct+'%':mode==='turnout'?'Affluenza '+x.turnout_pct+'%':esc(x.top_coalition||'—')}</span><small>${x.closed?'chiusa':'aperta'} · ${x.voters} votanti</small></div>`).join(''); heatTable.innerHTML=`<table><tr><th>Sez.</th><th>Top coalizione</th><th>Top lista</th><th>Sindaco</th><th>Affluenza</th><th>Disgiunti</th><th>Stato</th></tr>${rows.map(x=>`<tr><td>${esc(x.section)}</td><td>${esc(x.top_coalition||'—')} (${x.top_coalition_pct}%)</td><td>${esc(x.top_list||'—')} (${x.top_list_pct}%)</td><td>${esc(x.top_mayor||'—')} (${x.top_mayor_pct}%)</td><td>${x.turnout_pct}%</td><td>${x.split_vote_count} (${x.split_rate_pct}%)</td><td>${x.closed?'CHIUSA':'aperta'}</td></tr>`).join('')}</table>`}
function renderBodyGraph(){const limit=parseInt(graphLimit.value||45,10); const threshold=parseFloat(alertThreshold.value||25); const g=INTEL.body_graph; const nodes=g.nodes.slice().sort((a,b)=>b.weight-a.weight).slice(0,limit); const ids=new Set(nodes.map(n=>n.id)); const edges=g.edges.filter(e=>ids.has(e.source)&&ids.has(e.target)).slice(0,limit*2); const w=1000,h=540,cx=w/2,cy=h/2,r=220; const pos={}; nodes.forEach((n,i)=>{let a=2*Math.PI*i/nodes.length; pos[n.id]={x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}}); let svg=`<svg viewBox="0 0 ${w} ${h}" class="netSvg">`; edges.forEach(e=>{const a=pos[e.source],b=pos[e.target]; if(a&&b) svg+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke-width="${Math.max(1,Math.min(8,e.votes/5))}"/>`}); nodes.forEach(n=>{const p=pos[n.id]; const cls=n.type; svg+=`<g><circle class="${cls}" cx="${p.x}" cy="${p.y}" r="${Math.max(7,Math.min(24,7+n.weight/12))}"></circle><text x="${p.x+10}" y="${p.y+4}">${esc(n.label).slice(0,34)}</text></g>`}); svg+='</svg>'; networkGraph.innerHTML=svg; const alerts=g.alerts.filter(a=>a.section_pref_share_pct>=threshold); alertsBox.innerHTML=`<h3>Alert concentrazione preferenze</h3><table><tr><th>Candidato</th><th>Lista</th><th>Sezione</th><th>Voti</th><th>% preferenze sezione</th><th>Livello</th></tr>${alerts.map(a=>`<tr><td>${esc(a.candidate)}</td><td>${esc(a.list)}</td><td>${esc(a.section)}</td><td>${a.votes}</td><td>${a.section_pref_share_pct}%</td><td><span class="badge">${a.level}</span></td></tr>`).join('')}</table>`}
function destroy(c){if(c)c.destroy()}
function renderPrediction(){const p=INTEL.prediction; predictionBox.innerHTML=`<p><b>Metodo:</b> ${esc(p.method)}</p><p>Sezioni caricate: <b>${p.loaded_sections}</b> · chiuse: <b>${p.closed_sections}</b> · votanti osservati: <b>${p.observed_voters}</b> · votanti mancanti stimati: <b>${p.missing_voters_estimate}</b>.</p>`; destroy(predMayorChart); destroy(predListChart); predMayorChart=new Chart(predMayorChartEl(),{type:'bar',data:{labels:p.mayors.map(x=>x.name),datasets:[{label:'Proiezione sindaci',data:p.mayors.map(x=>x.projected)}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}}); predListChart=new Chart(predListChartEl(),{type:'bar',data:{labels:p.lists.slice(0,12).map(x=>x.name),datasets:[{label:'Proiezione liste',data:p.lists.slice(0,12).map(x=>x.projected)}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{ticks:{autoSkip:false,maxRotation:70,minRotation:30}},y:{beginAtZero:true}}}})}
function predMayorChartEl(){return document.getElementById('predMayorChart')} function predListChartEl(){return document.getElementById('predListChart')}
function renderWeight(){const q=(weightSearch.value||'').toLowerCase(), pf=profileFilter.value; const rows=INTEL.political_weight.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!pf||x.profile===pf)).slice(0,200); weightBox.innerHTML=`<table><tr><th>#</th><th>Candidato</th><th>Lista</th><th>Coalizione</th><th>Preferenze</th><th>% lista</th><th>Sezioni</th><th>Concentrazione</th><th>Indice body</th><th>Profilo</th></tr>${rows.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.candidate)}</b></td><td>${esc(x.list)}</td><td>${esc(x.coalition)}</td><td>${x.preferences}</td><td>${x.preference_on_list_pct}%</td><td>${x.sections_with_votes}</td><td>${x.concentration_pct}%</td><td><b>${x.body_index}</b></td><td><span class="badge">${esc(x.profile)}</span></td></tr>`).join('')}</table>`}
heatFilter.onchange=renderHeatmap; heatSearch.oninput=renderHeatmap; weightSearch.oninput=renderWeight; profileFilter.onchange=renderWeight; loadIntelligence();
