let state={modules:[],users:[],profiles:{},payments:[]};
async function api(url,opts){const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json'},...(opts||{})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Errore server');return d}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function loadAll(){const d=await api('/api/super/overview');state=d;renderModules();renderAdmins();renderPayments();loadProviders();}
function renderModules(){moduleGrid.innerHTML=state.modules.map(m=>`<div class="moduleCard ${m.enabled?'on':'off'}"><div class="moduleTop"><span class="badge">${esc(m.area)}</span><label class="switch"><input type="checkbox" data-key="${esc(m.key)}" ${m.enabled?'checked':''}><span></span></label></div><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p></div>`).join('')||'<p>Nessun modulo configurato.</p>';}
async function saveModulesFromSuper(){const cfg={};document.querySelectorAll('input[data-key]').forEach(i=>cfg[i.dataset.key]=i.checked);await api('/api/modules',{method:'POST',body:JSON.stringify({modules:cfg})});alert('Moduli aggiornati');await loadAll();}
async function createAdmin(){const payload={name:adminName.value,phone:adminPhone.value,pin:adminPin.value,organization:organization.value,place:place.value,cap:cap.value,province:province.value,region:region.value,usage_reason:usageReason.value,beneficiaries:beneficiaries.value,notes:notes.value};await api('/api/super/admins',{method:'POST',body:JSON.stringify(payload)});alert('Admin creato');['adminName','adminPhone','adminPin','organization','place','cap','province','region','usageReason','beneficiaries','notes'].forEach(id=>document.getElementById(id).value='');await loadAll();}
function renderAdmins(){const admins=state.users.filter(u=>u.role==='admin');adminsTable.innerHTML=`<table><thead><tr><th>Admin</th><th>Codice</th><th>Territorio</th><th>Motivo</th><th>Beneficiari</th><th>Stato</th></tr></thead><tbody>${admins.map(u=>{const p=state.profiles[String(u.id)]||{};return `<tr><td><b>${esc(u.name)}</b><br><span class="small">ID ${u.id}</span></td><td>${esc(u.phone)}</td><td>${esc(p.place)} ${esc(p.cap)}<br><span class="small">${esc(p.province)} ${esc(p.region)}</span></td><td>${esc(p.usage_reason)}</td><td>${esc(p.beneficiaries)}</td><td>${u.active?'Attivo':'Disattivo'}</td></tr>`}).join('')}</tbody></table>`;}
async function savePayment(){const payload={provider:payProvider.value,enabled:payEnabled.value==='true',mode:payMode.value,public_key:payPublicKey.value,webhook_url:payWebhook.value,notes:payNotes.value};await api('/api/super/payments',{method:'POST',body:JSON.stringify(payload)});alert('Metodo pagamento salvato');await loadAll();}
function renderPayments(){paymentsTable.innerHTML=state.payments.length?`<table><thead><tr><th>Provider</th><th>Stato</th><th>Modalità</th><th>Public key/Alias</th><th>Webhook</th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.provider)}</td><td>${p.enabled?'Abilitato':'Disabilitato'}</td><td>${esc(p.mode)}</td><td>${esc(p.public_key)}</td><td>${esc(p.webhook_url)}</td></tr>`).join('')}</tbody></table>`:'<p class="small">Nessun metodo salvato.</p>';}
async function loadProviders(){const d=await api('/api/super/payment-providers');providersTable.innerHTML=`<table><thead><tr><th>Provider</th><th>API</th><th>Variabili ambiente</th><th>Uso</th></tr></thead><tbody>${d.providers.map(p=>`<tr><td>${esc(p.provider)}</td><td>${esc(p.api)}</td><td>${p.env.map(esc).join('<br>')}</td><td>${esc(p.use)}</td></tr>`).join('')}</tbody></table>`;}
loadAll().catch(e=>alert(e.message));
